SpaceServerUniverse/UniverseCoreV2

- src/main/java/space/yurisi/universecorev2/subplugins/SubPluginInitializer.java
- src/main/java/space/yurisi/universecorev2/subplugins/salute/Salute.java
- src/main/java/space/yurisi/universecorev2/subplugins/salute/command/SaluteBaseCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/salute/command/kCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/salute/command/otiCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/salute/command/otuCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/suicide/Suicide.java
- src/main/java/space/yurisi/universecorev2/subplugins/suicide/command/suCommand.java
- src/main/resources/plugin.yml
> SaluteとSuicide

- src/main/java/space/yurisi/universecorev2/subplugins/SubPluginInitializer.java
- src/main/java/space/yurisi/universecorev2/subplugins/signcommand/SignCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/signcommand/event/InteractEvent.java
> SignCommand

- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/command/subcommand/visitSubCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/command/subcommand/visitlistSubCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/menu/list_menu/item/WarpMenuItem.java
> サブコマンド修正とサウンドエフェクト追加

- .github/workflows/ci.yaml
> fix(ci): CI で `ShadowJar` タスクを使うように

- src/main/java/space/yurisi/universecorev2/command/lobbyCommand.java
- src/main/java/space/yurisi/universecorev2/command/passwordCommand.java
- src/main/java/space/yurisi/universecorev2/command/pplayerCommand.java
- src/main/java/space/yurisi/universecorev2/event/player/LoginEvent.java
- src/main/java/space/yurisi/universecorev2/subplugins/levelaward/event/UpEvent.java
- src/main/java/space/yurisi/universecorev2/subplugins/levelsystem/command/addexpCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/levelsystem/listener/player/QuitEvent.java
- src/main/java/space/yurisi/universecorev2/subplugins/levelsystem/task/SaveDataTask.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/command/subcommand/listSubCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/menu/del_confirm_menu/DelConfirmMywarpInventoryMenu.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/menu/del_menu/DelMywarpInventoryMenu.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/menu/list_menu/ListMywarpInventoryMenu.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/menu/setting_menu/SettingMywarpInventoryMenu.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/menu/visit_menu/VisitMywarpInventoryMenu.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/menu/visit_menu/item/VisitMenuItem.java
- src/main/java/space/yurisi/universecorev2/subplugins/salute/command/otiCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/salute/command/otuCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universedice/command/UniverseDiceCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeland/command/LandCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeland/event/player/TouchEvent.java
- src/main/java/space/yurisi/universecorev2/subplugins/xtpsystem/command/XtpCommand.java
- src/main/java/space/yurisi/universecorev2/utils/Message.java
MyWarp 以外のメッセージを [なんとかAI] みたいなフォーマットに統一した
IDE の検索機能を使って一つ一つ書き換えたので漏れがあったらその都度パッチ当てます
> WIP - feat: プラグインメッセージを統一化

- src/main/java/space/yurisi/universecorev2/item/solar_system/SolarSystemAxe.java
- src/main/java/space/yurisi/universecorev2/item/solar_system/SolarSystemPickaxe.java
- src/main/java/space/yurisi/universecorev2/item/solar_system/SolarSystemShovel.java
- src/main/java/space/yurisi/universecorev2/item/solar_system/SolarSystemSword.java
> rewrite `new ItemStack` into `ItemStack.of`

- src/main/java/space/yurisi/universecorev2/command/passwordCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/levelsystem/command/addexpCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/Mywarp.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/command/MywarpCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeeconomy/command/addmoneyCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeeconomy/command/payCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeeconomy/command/reducemoneyCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeeconomy/command/seemoneyCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeeconomy/command/setmoneyCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/xtpsystem/command/XtpCommand.java
- src/main/resources/plugin.yml
`plugin.yml` から `usage` キーを削除し, 引数不足のとき独自メッセージで伝えるように
> chore: Usage を削除し, 独自のヘルプを追加

- LICENSE
> chore: GPLv3 で再ライセンスする

- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/Mywarp.java
- src/main/java/space/yurisi/universecorev2/subplugins/mywarp/command/MywarpCommand.java
- src/main/resources/plugin.yml
同一コマンドだったのでエイリアスコマンドに置き換えて早くしました
多分インベントリ(メニュー)開くのちょっと軽くなったと思う
> perf: エイリアスコマンドに置き換えて最適化

- src/main/java/space/yurisi/universecorev2/database/repositories/MywarpRepository.java
- src/main/java/space/yurisi/universecorev2/database/repositories/PlayerNormalLevelRepository.java
ref: #62 , #63 
Javadoc の生成が出来ないのを修正した (が, 警告が大量に残ってるのでそれは直したほうがいい)
#62 , #63 を話し合うのはそれ以降
> build(fix): Javadoc が生成出来るように

- src/main/java/space/yurisi/universecorev2/utils/Message.java
close #70 
```java
Message.sendNormalMessage(player, "[管理AI]", "[ここをクリックして土地を購入]", ClickEvent.runCommand("/land buy"), "クリックすると土地を購入します")
```
> feat: `Message.sendNormalMessage` でコンポーネントが使えるように

- src/main/java/space/yurisi/universecorev2/subplugins/freemarket/command/marketCommand.java
> 手に持ったアイテムがほかのスロットにもあったら消されるトンデモないバグ直し

- src/main/java/space/yurisi/universecorev2/subplugins/containerprotect/event/player/TouchEvent.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeland/event/entity/DamageEvent.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeland/event/player/TouchEvent.java
権限のないプレイヤーが額縁を回転できてしまう問題を修正しました
> UniverseLand: 額縁回転問題

- src/main/java/space/yurisi/universecorev2/subplugins/signcommand/SignCommand.java
- src/main/java/space/yurisi/universecorev2/subplugins/signcommand/event/InteractEvent.java
シフトしてるときに左クリックで破壊と右クリックで編集できるように
> シフトしてない状態で右クリック左クリックコマンド発動

- src/main/java/space/yurisi/universecorev2/subplugins/universeland/command/LandCommand.java
- Operators can now delete land
> UniverseLand: 権限者が土地を削除できるように

- src/main/java/space/yurisi/universecorev2/command/CommandManager.java
- src/main/java/space/yurisi/universecorev2/command/menuCommand.java
- src/main/java/space/yurisi/universecorev2/menu/MainMenu.java
- src/main/java/space/yurisi/universecorev2/utils/TimeHelper.java
- src/main/java/space/yurisi/universecorev2/utils/time_type/TimeType.java
- src/main/resources/plugin.yml
> feat: メニューの追加

- src/main/resources/plugin.yml
LuckPerms で一括管理しているため, パーミッションをすべて削除しました. 本番環境側はすでに修正済みですが, 誤りがあったらちゃしゃ猫ごめんなさい券を使います
> chore: コマンド欄を修正

- src/main/java/space/yurisi/universecorev2/menu/MainMenu.java
- src/main/java/space/yurisi/universecorev2/menu/menu_item/main_menu/LaunchNavigationItem.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeguns/UniverseGuns.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeguns/core/GunCommand.java
- src/main/java/space/yurisi/universecorev2/utils/TimeHelper.java
- src/main/java/space/yurisi/universecorev2/utils/time_type/TimeType.java
- src/main/resources/plugin.yml
> feat: 弾薬メニューをメニューから開けるように

- src/main/java/space/yurisi/universecorev2/event/player/InteractEvent.java
> fix: すべてのブロックに対して利用制限が加わっていた問題の修正

- src/main/java/space/yurisi/universecorev2/subplugins/containerprotect/event/player/TouchEvent.java
> 俺はもっとロックに生きる。

- src/main/java/space/yurisi/universecorev2/item/UniverseItem.java
- src/main/java/space/yurisi/universecorev2/item/gun/F2.java
- src/main/java/space/yurisi/universecorev2/item/gun/Gun.java
- src/main/java/space/yurisi/universecorev2/item/gun/L96A1.java
- src/main/java/space/yurisi/universecorev2/item/gun/M1911.java
- src/main/java/space/yurisi/universecorev2/item/gun/M870.java
- src/main/java/space/yurisi/universecorev2/item/gun/R4C.java
- src/main/java/space/yurisi/universecorev2/item/gun/RPG.java
- src/main/java/space/yurisi/universecorev2/item/gun/SMG11.java
- src/main/java/space/yurisi/universecorev2/item/gun/TacticalLeggings.java
- src/main/java/space/yurisi/universecorev2/menu/MainMenu.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeguns/event/GunEvent.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeguns/event/GunShot.java
- src/main/java/space/yurisi/universecorev2/subplugins/universeguns/event/ShotgunShot.java
> M1911とタクティカルレギンス実装，説明文追加，弾丸テクスチャ割り当て
